# Go To Jekyll
title: Your awesome title
description: > # this means to ignore newlines until "baseurl:"
  Description of site here

logo: http://placehold.it/300
favicon: http://placehold.it/15
image: http://placehold.it/300
email: your-email@domain.com

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# GitHub
github_username: robyremzy
# repository: robyremzy/robyremzy.github.io

author:
  name: Rémi Roubin
  email: hi@rroubin.fr
  uri: https://rroubin.fr
  twitter: remstw

timezone: Europe/Paris

# Build settings
permalink: pretty
sass:
  style: :compressed
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: true
gems:
  # - jekyll-feed
  - jemoji
  # - jekyll-gist
  # - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - node_modules
  - .sass-cache
